## 1
SELECT G.MAGV
FROM GIAOVIEN G
WHERE HOTEN LIKE 'Nguyễn%'
  AND G.LUONG > 2000
UNION DISTINCT
SELECT TRUONGBM AS MAGV
FROM BOMON B
WHERE YEAR(B.NGAYNHANCHUC) >1995

## 2
SELECT G.HOTEN,
       B.TENBM
FROM GIAOVIEN G
JOIN BOMON B ON G.MABM = B.MABM;

## 3
SELECT G.HOTEN
FROM GIAOVIEN G
JOIN BOMON B ON G.MABM = B.MABM
AND B.TENBM ='Hệ thống thông tin'
ORDER BY G.NGSINH
LIMIT 1;

## 4
WITH DATA AS (
  SELECT 
    G.HOTEN, 
    COUNT(*) AS SOLUONG 
  FROM 
    GIAOVIEN G 
    JOIN DETAI D ON G.MAGV = D.GVCNDT 
  GROUP BY 
    G.HOTEN
) 
SELECT 
  HOTEN 
FROM 
  DATA 
WHERE 
  SOLUONG IN(
    SELECT 
      MAX(SOLUONG) 
    FROM 
      DATA
  )
;

## 5
WITH DATA AS (
	SELECT
		G.HOTEN,
		G.MABM,
		COUNT(DISTINCT (D.TENDT)) AS SOLUONG
	FROM
		THAMGIADT T
		JOIN GIAOVIEN G ON T.MAGV = G.MAGV
		JOIN DETAI D ON T.MADT = D.MADT
	GROUP BY
		G.HOTEN,
		G.MABM
)
SELECT
	DT.HOTEN,
	BM.TENBM
FROM (
	SELECT
		HOTEN,
		MABM
	FROM
		DATA
	WHERE
		SOLUONG IN(
			SELECT
				MAX(SOLUONG)
				FROM DATA)) AS DT
	JOIN BOMON AS BM ON DT.MABM = BM.MABM



## 6
WITH DATA AS(
  SELECT 
    DISTINCT D.TENDT, 
    G.MAGV 
  FROM 
    THAMGIADT T 
    JOIN DETAI D ON T.MADT = D.MADT 
    JOIN GIAOVIEN G ON T.MAGV = G.MAGV 
  WHERE 
    G.MABM = 'HTTT'
), 
TENDT_SL AS (
  SELECT 
    TENDT, 
    COUNT(MAGV) AS SOLUONG 
  FROM 
    DATA 
  GROUP BY 
    TENDT
) 
SELECT 
  TENDT 
FROM 
  TENDT_SL 
WHERE 
  SOLUONG IN (
    SELECT 
      COUNT(*) AS SOLUONGHTTT 
    FROM 
      GIAOVIEN 
    WHERE 
      MABM = 'HTTT'
  );


## 7
WITH GVCN AS (
  SELECT 
    D.MADT, 
    D.TENDT 
  FROM 
    DETAI D 
    JOIN GIAOVIEN G ON D.GVCNDT = G.MAGV 
  WHERE 
    HOTEN = 'Trần Trà Hương'
), 
GVTG AS(
  SELECT 
    DISTINCT GV.MADT, 
    T.MAGV, 
    G.HOTEN 
  FROM 
    GVCN AS GV 
    JOIN THAMGIADT AS T ON GV.MADT = T.MADT 
    JOIN GIAOVIEN G ON T.MAGV = G.MAGV
), 
GV_SOLUONGDT AS (
  SELECT 
    GT.MAGV, 
    GT.HOTEN, 
    COUNT(GT.MADT) AS SOLUONGDT 
  FROM 
    GVTG AS GT 
  GROUP BY 
    GT.MAGV, 
    GT.HOTEN
) 
SELECT 
  HOTEN 
FROM 
  GV_SOLUONGDT 
WHERE 
  SOLUONGDT IN(
    SELECT 
      COUNT(*) 
    FROM 
      GVCN
  )




## 8
WITH GVCNTT AS(
  SELECT 
    G.HOTEN, 
    K.MAKHOA, 
    G.MAGV 
  FROM 
    BOMON B 
    JOIN GIAOVIEN G ON G.MABM = B.MABM 
    JOIN KHOA K ON B.MAKHOA = K.MAKHOA 
  WHERE 
    K.MAKHOA = 'CNTT'
), 
DT_CNTT AS (
  SELECT 
    DISTINCT T.MADT, 
    GVCNTT.MAGV 
  FROM 
    GVCNTT 
    JOIN THAMGIADT T ON GVCNTT.MAGV = T.MAGV
), 
DT_SL_GVCNTT AS (
  SELECT 
    MADT, 
    COUNT(MAGV) AS SOLUONG_GVCNTT 
  FROM 
    DT_CNTT 
  GROUP BY 
    MADT
), 
MA_DT AS(
  SELECT 
    T1.MADT 
  FROM 
    DT_SL_GVCNTT AS T1 
  WHERE 
    T1.SOLUONG_GVCNTT IN (
      SELECT 
        COUNT(T2.MAGV) 
      FROM 
        GVCNTT AS T2
    )
) 
SELECT 
  D.TENDT 
FROM 
  MA_DT AS MA 
  JOIN DETAI AS D ON MA.MADT = D.MADT;

## 9
WITH GVSH AS(
  SELECT 
    G.HOTEN, 
    K.MAKHOA, 
    G.MAGV 
  FROM 
    BOMON B 
    JOIN GIAOVIEN G ON G.MABM = B.MABM 
    JOIN KHOA K ON B.MAKHOA = K.MAKHOA 
  WHERE 
    K.MAKHOA = 'SH'
), 
DT_SH AS (
  SELECT 
    DISTINCT T.MADT, 
    GVSH.MAGV 
  FROM 
    GVSH 
    JOIN THAMGIADT T ON GVSH.MAGV = T.MAGV
), 
DT_SL_GVSH AS (
  SELECT 
    MADT, 
    COUNT(MAGV) AS SOLUONG_GVSH 
  FROM 
    DT_SH 
  GROUP BY 
    MADT
), 
MA_DT AS(
  SELECT 
    T1.MADT 
  FROM 
    DT_SL_GVSH AS T1 
  WHERE 
    T1.SOLUONG_GVSH IN (
      SELECT 
        COUNT(T2.MAGV) 
      FROM 
        GVSH AS T2
    )
) 
SELECT 
  D.TENDT 
FROM 
  MA_DT AS MA 
  JOIN DETAI AS D ON MA.MADT = D.MADT;

## 10
WITH DETAI_CD_NKPT AS (
  SELECT 
    MADT 
  FROM 
    DETAI DT 
    JOIN CHUDE CD ON DT.MACD = CD.MACD 
  WHERE 
    CD.TENCD = 'Nghiên cứu phát triển'
), 
SOLUONG_DETAI_CD_NKPT AS (
  SELECT 
    COUNT(
      DISTINCT(MADT)
    ) SL_DT_CD_NKPT 
  FROM 
    DETAI_CD_NKPT
), 
MAGV_SOLUONGDT_CD_NKPT AS (
  SELECT 
    TGDT.MAGV, 
    COUNT(
      DISTINCT(TGDT.MADT)
    ) AS SL_DT_CD_NKPT 
  FROM 
    THAMGIADT TGDT 
    JOIN DETAI_CD_NKPT ON TGDT.MADT = DETAI_CD_NKPT.MADT 
  GROUP BY 
    TGDT.MAGV
), 
GV_THOA_DK AS (
  SELECT 
    MAGV 
  FROM 
    MAGV_SOLUONGDT_CD_NKPT 
  WHERE 
    SL_DT_CD_NKPT IN (
      SELECT 
        * 
      FROM 
        SOLUONG_DETAI_CD_NKPT
    )
) 
SELECT 
  T2.MAGV, 
  T2.HOTEN, 
  T3.TENBM, 
  T4.HOTEN AS TEN_GVQLCM 
FROM 
  GV_THOA_DK T1 
  JOIN GIAOVIEN T2 ON T1.MAGV = T2.MAGV 
  JOIN BOMON T3 ON T2.MABM = T3.MABM 
  JOIN GIAOVIEN T4 ON T2.GVQLCM = T4.MAGV

